## Github RESTful API Examples
@username = Enter-name-of-authenticated-user
@password = Enter-authenticated-user-token-or-password
@userrepo = Enter-repository-user-name
@reponame = Enter-repository-name

GET https://api.github.com
Authorization: Basic {{username}} {{password}}

GET https://api.github.com/user/repos
Authorization: Basic {{username}} {{password}}

GET https://api.github.com/repos/{{userrepo}}/{{reponame}}/subscription
Authorization: Basic {{username}} {{password}}

GET https://api.github.com/repos/{{userrepo}}/{{reponame}}/subscribers
Authorization: Basic {{username}} {{password}}

POST https://api.github.com/user/repos
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "name" : "rest-api-repo-create-test"
}