//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinHttpClient.rc
//
#define IDS_RESOURCE_STRING_MISSING     103
#define IDS_WIN_HTTP_CLIENT             104
#define IDS_CLOSE_QUESTION              105
#define IDS_CLOSE                       106
#define IDS_PROTO_HTTP                  107
#define IDS_PROTO_HTTPS                 108
#define IDS_PROTOCOL_TEXT               109
#define IDS_ACCESS_TYPE_TEXT            110
#define IDS_ACCESS_TYPE_NO_PROXY        111
#define IDS_ACCESS_TYPE_NAMED_PROXY     112
#define IDS_ACCESS_TYPE_AUTOMATIC_PROXY 113
#define IDS_PROXY_INFORMATION_TEXT      114
#define IDS_ADDITIONAL_HEADERS_TEXT     114
#define IDS_PROXY_NAME_TEXT             115
#define IDS_PROXY_ACCESS_TYPE_TEXT      115
#define IDS_ACCESS_TYPE_NO_PROXY_NAME   116
#define IDS_PROXY_BYPASS_TEXT           117
#define IDS_ACCESS_TYPE_NO_PROXY_BYPASS 118
#define IDS_APPLICATION_NAME            119
#define IDS_SERVER_NAME_TEXT            120
#define IDS_SERVER_NAME_SAMPLE          121
#define IDS_SERVER_PORT_TEXT            122
#define IDS_SERVER_PORT_HTTP_DEFAULT    123
#define IDS_SERVER_PORT_HTTPS_DEFAULT   124
#define IDS_SERVER_PORT_DEFAULT         125
#define IDS_VERB_TEXT                   126
#define IDS_VERB_GET                    127
#define IDS_VERB_POST                   128
#define IDS_VERB_PUT                    129
#define IDS_VERB_DELETE                 130
#define IDS_VERB_HEAD                   131
#define IDS_VERB_OPTIONS                132
#define IDS_VERB_PATCH                  133
#define IDS_VERB_CONNECT                134
#define IDS_VERB_TRACE                  135
#define IDS_HTTP_VERSION_TEXT           136
#define IDS_REFERRER_TEXT               137
#define IDS_ACCEPT_TYPES_TEXT           138
#define IDS_FLAGS_TEXT                  139
#define IDS_HTTP_VERSION_DEFAULT        140
#define IDS_REFERRER_DEFAULT            141
#define IDS_ACCEPT_TYPES_DEFAULT        142
#define IDS_FLAGS_SECURE                143
#define IDS_FLAGS_BYPASS_PROXY_CACHE    144
#define IDS_FLAGS_ESCAPE_DISABLED       145
#define IDS_FLAGS_ESCAPE_PERCENT        146
#define IDS_FLAGS_ESCAPE_DISABLED_QUERY 147
#define IDS_FLAGS_NULL_CODEPAGE         148
#define IDS_FLAGS_REFRESH               149
#define IDS_PATH_TEXT                   150
#define IDS_PATH_SAMPLE                 151
#define IDS_AUTH_STATIC_TEXT            152
#define IDS_AUTH_TEXT                   152
#define IDS_AUTH_NONE                   153
#define IDS_AUTH_BASIC                  154
#define IDS_AUTH_NTLM                   155
#define IDS_AUTH_PASSPORT               156
#define IDS_AUTH_DIGEST                 157
#define IDS_AUTH_NEGOTIATE              158
#define IDS_AUTH_SCHEME                 159
#define IDS_AUTH_SCHEME_TEXT            159
#define IDS_OPTIONAL_REQUEST_DATA_TEXT  159
#define IDS_USERNAME_TEXT               160
#define IDS_PASSWORD_TOKEN_TEXT         161
#define IDS_APP_NAME_SAMPLE             162
#define IDC_HttpCombo                   1001
#define IDC_ProtocolCombo               1001
#define IDC_ProtoStaticText             1002
#define IDC_AppNameStaticText           1003
#define IDC_AppNameEditbox              1004
#define IDC_AccessTypeStaticText        1006
#define IDC_AccessTypeCombo             1007
#define IDC_ProxyNameStaticText         1008
#define IDC_ProxyNameCombo              1012
#define IDC_ProxyBypassCombo            1013
#define IDC_ProxyBypassStaticText       1014
#define IDC_ServerNameEditBox           1015
#define IDC_ServerNameStaticText        1016
#define IDC_ServerPortCombo             1018
#define IDC_ServerPortStaticText        1019
#define IDC_VerbStaticText              1020
#define IDC_VerbCombo                   1021
#define IDC_PathEditBox                 1022
#define IDC_PathStaticText              1023
#define IDC_HttpVersionStaticText       1024
#define IDC_ReferrerStaticText          1025
#define IDC_AcceptTypesStaticText       1026
#define IDC_FlagsStaticText             1027
#define IDC_FlagsListBox                1028
#define IDC_HttpVersionComboBox         1032
#define IDC_ReferrerComboBox            1033
#define IDC_AcceptTypesComboBox         1034
#define IDC_AuthSchemeStaticText        1035
#define IDC_AuthSchemeComboBox          1036
#define IDC_UserNameEditBox             1037
#define IDC_PasswordEditBox             1038
#define IDC_UsernameStaticText          1039
#define IDC_PasswordStaticText          1040
#define IDC_AuthorizationGroupBox       1041
#define IDC_ProxyAccessTypeStaticText   1042
#define IDC_AdditionalHeadersEditBox    1045
#define IDC_AdditionalHeadersCheckBox   1046
#define IDC_OptionalRequestDataCheckBox 1047
#define IDC_EDIT2                       1048
#define IDD_HttpClientMainDialog        10001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10003
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
